### ISSUE TITLE
Error while executing  Dicom to FHIR converter-0.1.0-all.jar 

### ISSUE THREAD

**Issue by rpydimarri-mw** [GoogleCloudPlatform/healthcare-data-harmonization-dataflow#17]
HL7 to FHIR converter did not give any issues but running into this issue with Dicom. Using Same environment.

Exception in thread "main" java.lang.IllegalStateException: Unable to return a default Coder for MapMessages.mapping [PCollection@492045670]. Correct one of the following root causes:
  No Coder has been manually specified;  you may do so using .setCoder().
  Inferring a Coder from the CoderRegistry failed: Unable to provide a Coder for com.google.cloud.healthcare.etl.model.mapping.MappingOutput.
  Building a Coder using a registered CoderProvider failed.
  See suppressed exceptions for detailed failures.
  Using the default output Coder from the producing PTransform failed: PTransform.getOutputCoder called.
        at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at org.apache.beam.sdk.values.PCollection.getCoder(PCollection.java:280)
        at org.apache.beam.sdk.values.PCollection.finishSpecifying(PCollection.java:117)
        at org.apache.beam.sdk.runners.TransformHierarchy.finishSpecifyingInput(TransformHierarchy.java:153)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:546)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:481)
        at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:357)
        at com.google.cloud.healthcare.etl.runner.dicomtofhir.DicomToFhirStreamingRunner.mapDicomStudyMetadataToFhirResource(DicomToFhirStreamingRunner.java:278)
        at com.google.cloud.healthcare.etl.runner.dicomtofhir.DicomToFhirStreamingRunner.main(DicomToFhirStreamingRunner.java:328)

**Comment by vneilley** [comment]
@jasonklotzer

**Comment by msbukal** [comment]
Newest commit (https://github.com/GoogleCloudPlatform/healthcare-data-harmonization-dataflow/commit/c6747936807f4cc967e052a3471b036c63b71fb3) should fix this.
